F1::Run "C:\Documents and Settings\Administrator\桌面\全套\一键无整形.exe"
F2::Run "C:\Documents and Settings\Administrator\桌面\全套\一键20000.exe"
F3::Run "C:\Documents and Settings\Administrator\桌面\全套\一键26000.exe"
F4::Run "C:\Documents and Settings\Administrator\桌面\全套\一键启动TCPZ.exe"
F5::Run "C:\Documents and Settings\Administrator\桌面\全套\一键启动流量矿石.exe"
F6::Run "C:\Documents and Settings\Administrator\桌面\全套\一键启动卡淘金.exe"
F7::Run "C:\Documents and Settings\Administrator\桌面\全套\一键打开锐速统计.exe"
