F1::Run "C:\Documents and Settings\Administrator\桌面\全套\一键无整形.exe"
F2::Run "C:\Documents and Settings\Administrator\桌面\全套\一键20000.exe"
F3::Run "C:\Documents and Settings\Administrator\桌面\全套\一键26000.exe"
F4::Run "C:\Documents and Settings\Administrator\桌面\全套\tcpz_20090406\tcpz.exe"
F5::Run "C:\Program Files\Miner\Miner.exe"
F6::Run "C:\Documents and Settings\Administrator\桌面\全套\卡淘金.exe"
